Translating the technical test to english
MeilleursAgents/backend-technical-test pull request #12
Opened 2022-05-30 12:48 UTC by quentinus95

2022-07-18 15:03 UTC, Yoan-MA commented on README.md
> +The number of pages is different for each arrondissement: from zero to dozens of pages. You will have to imagine a mechanism that can be adapted to the number of pages to browse. There are multiple i
```suggestion
The number of pages is different for each district: from zero to dozens of pages. You will have to imagine a mechanism that can be adapted to the number of pages to browse. There are multiple implementations possible.
```

2022-07-18 15:04 UTC, Yoan-MA commented on README.md
> +- `place_id`: arrondissement identifier (as passed in the query parameters);
```suggestion
- `place_id`: district identifier (as passed in the query parameters);
```

2022-07-18 15:07 UTC, Yoan-MA commented on README.md
> +For each arrondissement, the average price per real square meter is computed, to be displayed on the website.
```suggestion
For each district, the average price per square meter is computed, to be displayed on the website.
```

2022-07-18 15:26 UTC, quentinus95 commented on README.md
> +The objective is to build a price map of the average selling prices (€/m²) per arrondissment in Paris, with statistics, from an API of listings from MeilleursAgents.
I would go for MeilleursAgents and go for a global MA-to-AVIV change later on

2022-07-18 15:43 UTC, Yoan-MA commented
sure, go ahead ! Maybe we could put the word in italic to indicate that it's a french word ?

All my suggestions are not about `arrondissement` and `districts`. Please take a look on the others 🙏

2022-08-17 07:58 UTC, corenting requested changes

2022-08-17 07:58 UTC, corenting commented on README.md
> +**You must not change the `listingapi`, it only serves at exposing data.**
```suggestion
**You must not change the `listingapi`, it is only used to expose data.**
```

2022-08-17 07:58 UTC, corenting commented on README.md
> +To get started, a first implementation already exists in the `app.py` file. This code adds a `/update_data` endpoint to the `pricemap` app, which starts data retrieval.
To linked to the translation, but:
```suggestion
To get started, a first implementation already exists in the `app.py` file. This code adds a `/update_data` endpoint to the `pricemap` app, which starts the data retrieval process. If you feels it is necessary to change the way the data retrevial process is started, don't hesitate to change it.
```

2022-08-17 07:58 UTC, corenting commented on usages.md
> +This should not be necessary as done automatically on first start, but can allow to force the rebuilt of the apps.
```suggestion
This should not be necessary as done automatically on first start, but can allow to force the rebuild of the apps.
```

2022-08-17 07:58 UTC, corenting commented on usages.md
> +Destroys application containers. Useful as `docker-compose` reuses already existing containers by default.
```suggestion
Destroy application containers. Useful as `docker-compose` reuses already existing containers by default.
```

2022-08-17 07:58 UTC, corenting commented on usages.md
> +To inter in the shell of the app and run manual commands.
```suggestion
To enter the shell of the app container and run manual commands.
```

2022-08-18 10:11 UTC, Yoan-MA approved these changes
🚀

2022-08-23 07:52 UTC, merged